CREATE TABLE IF NOT EXISTS ratings (
    rating_id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS users (
    user_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50),
    name varchar(50),
    email varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS films (
    film_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    description text,
    releaseDate date,
    duration int4,
    rating_id int4 REFERENCES ratings(rating_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id int8 REFERENCES films(film_id),
    genre_id int4 REFERENCES genres(genre_id),
    PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendship (
    userOne_id int8 REFERENCES users(user_id),
    userTwo_id int8 REFERENCES users(user_id),
    PRIMARY KEY (userOne_id, userTwo_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id int8 REFERENCES films(film_id),
    user_id int8 REFERENCES users(user_id),
    PRIMARY KEY(film_id, user_id)
)
