INSERT INTO GENRES (name) VALUES ('Комедия');
INSERT INTO GENRES (name) VALUES ('Драма');
INSERT INTO GENRES (name) VALUES ('Мультфильм');
INSERT INTO GENRES (name) VALUES ('Триллер');
INSERT INTO GENRES (name) VALUES ('Документальный');
INSERT INTO GENRES (name) VALUES ('Боевик');

INSERT INTO RATINGS (name) VALUES ('G');
INSERT INTO RATINGS (name) VALUES ('PG');
INSERT INTO RATINGS (name) VALUES ('PG-13');
INSERT INTO RATINGS (name) VALUES ('R');
INSERT INTO RATINGS (name) VALUES ('NC-17');